version: 2

jobs:
  build:
    docker:
      image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            
      - run:
          shell: "/bin/bash -eo pipefail"
          name: Install Dependencies
          command: npm i --quiet
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          shell: "/bin/bash -eo pipefail"
          name: Run tests
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm run test --reporter-options token=${TOKEN}

